# # DO NOT EDIT THIS FILE!
# #
# # This file is generated from the CDP specification using AST. If you need to make
# # changes, edit the generator and regenerate all of the modules.

from __future__ import annotations
"""CDP domain: DeviceOrientation (experimental)"""
import typing
import enum
from .util import T_JSON_DICT
None


def clear_device_orientation_override() ->typing.Generator[T_JSON_DICT,
    T_JSON_DICT, None]:
    """Clears the overridden Device Orientation."""
    cmd_dict = {'method': 'DeviceOrientation.clearDeviceOrientationOverride'}
    json_result = yield cmd_dict
    return None


def set_device_orientation_override(alpha: float, beta: float, gamma: float
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Overrides the Device Orientation.

:param ...:

:param alpha: Mock alpha

:param beta: Mock beta

:param gamma: Mock gamma"""
    params_dict: T_JSON_DICT = dict()
    params_dict['alpha'] = alpha
    params_dict['beta'] = beta
    params_dict['gamma'] = gamma
    cmd_dict = {'method': 'DeviceOrientation.setDeviceOrientationOverride',
        'params': params_dict}
    json_result = yield cmd_dict
    return None
