# # DO NOT EDIT THIS FILE!
# #
# # This file is generated from the CDP specification using AST. If you need to make
# # changes, edit the generator and regenerate all of the modules.

from __future__ import annotations
"""CDP domain: WebAuthn (experimental)

This domain allows configuring virtual authenticators to test the WebAuthn
API."""
import typing
import enum
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
None


@dataclass
class Credential:
    credential_id: str
    is_resident_credential: bool
    private_key: str
    sign_count: int
    rp_id: typing.Optional[str] = None
    user_handle: typing.Optional[str] = None
    large_blob: typing.Optional[str] = None
    backup_eligibility: typing.Optional[bool] = None
    backup_state: typing.Optional[bool] = None
    user_name: typing.Optional[str] = None
    user_display_name: typing.Optional[str] = None

    def to_json(self) ->T_JSON_DICT:
        json_data: T_JSON_DICT = dict()
        json_data['credentialId'] = self.credential_id
        json_data['isResidentCredential'] = self.is_resident_credential
        json_data['privateKey'] = self.private_key
        json_data['signCount'] = self.sign_count
        if self.rp_id is not None:
            json_data['rpId'] = self.rp_id
        if self.user_handle is not None:
            json_data['userHandle'] = self.user_handle
        if self.large_blob is not None:
            json_data['largeBlob'] = self.large_blob
        if self.backup_eligibility is not None:
            json_data['backupEligibility'] = self.backup_eligibility
        if self.backup_state is not None:
            json_data['backupState'] = self.backup_state
        if self.user_name is not None:
            json_data['userName'] = self.user_name
        if self.user_display_name is not None:
            json_data['userDisplayName'] = self.user_display_name
        return json_data

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->Credential:
        return cls(credential_id=json_obj['credentialId'],
            is_resident_credential=json_obj['isResidentCredential'],
            private_key=json_obj['privateKey'], sign_count=json_obj[
            'signCount'], rp_id=json_obj['rpId'] if json_obj.get('rpId') is not
            None else None, user_handle=json_obj['userHandle'] if json_obj.
            get('userHandle') is not None else None, large_blob=json_obj[
            'largeBlob'] if json_obj.get('largeBlob') is not None else None,
            backup_eligibility=json_obj['backupEligibility'] if json_obj.
            get('backupEligibility') is not None else None, backup_state=
            json_obj['backupState'] if json_obj.get('backupState') is not
            None else None, user_name=json_obj['userName'] if json_obj.get(
            'userName') is not None else None, user_display_name=json_obj[
            'userDisplayName'] if json_obj.get('userDisplayName') is not
            None else None)


@dataclass
class VirtualAuthenticatorOptions:
    protocol: AuthenticatorProtocol
    transport: AuthenticatorTransport
    ctap2_version: typing.Optional[Ctap2Version] = None
    has_resident_key: typing.Optional[bool] = None
    has_user_verification: typing.Optional[bool] = None
    has_large_blob: typing.Optional[bool] = None
    has_cred_blob: typing.Optional[bool] = None
    has_min_pin_length: typing.Optional[bool] = None
    has_prf: typing.Optional[bool] = None
    automatic_presence_simulation: typing.Optional[bool] = None
    is_user_verified: typing.Optional[bool] = None
    default_backup_eligibility: typing.Optional[bool] = None
    default_backup_state: typing.Optional[bool] = None

    def to_json(self) ->T_JSON_DICT:
        json_data: T_JSON_DICT = dict()
        json_data['protocol'] = self.protocol.to_json()
        json_data['transport'] = self.transport.to_json()
        if self.ctap2_version is not None:
            json_data['ctap2Version'] = self.ctap2_version.to_json()
        if self.has_resident_key is not None:
            json_data['hasResidentKey'] = self.has_resident_key
        if self.has_user_verification is not None:
            json_data['hasUserVerification'] = self.has_user_verification
        if self.has_large_blob is not None:
            json_data['hasLargeBlob'] = self.has_large_blob
        if self.has_cred_blob is not None:
            json_data['hasCredBlob'] = self.has_cred_blob
        if self.has_min_pin_length is not None:
            json_data['hasMinPinLength'] = self.has_min_pin_length
        if self.has_prf is not None:
            json_data['hasPrf'] = self.has_prf
        if self.automatic_presence_simulation is not None:
            json_data['automaticPresenceSimulation'
                ] = self.automatic_presence_simulation
        if self.is_user_verified is not None:
            json_data['isUserVerified'] = self.is_user_verified
        if self.default_backup_eligibility is not None:
            json_data['defaultBackupEligibility'
                ] = self.default_backup_eligibility
        if self.default_backup_state is not None:
            json_data['defaultBackupState'] = self.default_backup_state
        return json_data

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->VirtualAuthenticatorOptions:
        return cls(protocol=AuthenticatorProtocol.from_json(json_obj[
            'protocol']), transport=AuthenticatorTransport.from_json(
            json_obj['transport']), ctap2_version=Ctap2Version.from_json(
            json_obj['ctap2Version']) if json_obj.get('ctap2Version') is not
            None else None, has_resident_key=json_obj['hasResidentKey'] if 
            json_obj.get('hasResidentKey') is not None else None,
            has_user_verification=json_obj['hasUserVerification'] if 
            json_obj.get('hasUserVerification') is not None else None,
            has_large_blob=json_obj['hasLargeBlob'] if json_obj.get(
            'hasLargeBlob') is not None else None, has_cred_blob=json_obj[
            'hasCredBlob'] if json_obj.get('hasCredBlob') is not None else
            None, has_min_pin_length=json_obj['hasMinPinLength'] if 
            json_obj.get('hasMinPinLength') is not None else None, has_prf=
            json_obj['hasPrf'] if json_obj.get('hasPrf') is not None else
            None, automatic_presence_simulation=json_obj[
            'automaticPresenceSimulation'] if json_obj.get(
            'automaticPresenceSimulation') is not None else None,
            is_user_verified=json_obj['isUserVerified'] if json_obj.get(
            'isUserVerified') is not None else None,
            default_backup_eligibility=json_obj['defaultBackupEligibility'] if
            json_obj.get('defaultBackupEligibility') is not None else None,
            default_backup_state=json_obj['defaultBackupState'] if json_obj
            .get('defaultBackupState') is not None else None)


class AuthenticatorProtocol(enum.Enum):
    U2F = 'u2f'
    CTAP2 = 'ctap2'

    @classmethod
    def from_json(cls, json: str) ->AuthenticatorProtocol:
        return cls(json)

    def to_json(self) ->str:
        return self.value

    def __repr__(self) ->str:
        return '<AuthenticatorProtocol.{}>'.format(self.value)


class AuthenticatorTransport(enum.Enum):
    USB = 'usb'
    NFC = 'nfc'
    BLE = 'ble'
    CABLE = 'cable'
    INTERNAL = 'internal'

    @classmethod
    def from_json(cls, json: str) ->AuthenticatorTransport:
        return cls(json)

    def to_json(self) ->str:
        return self.value

    def __repr__(self) ->str:
        return '<AuthenticatorTransport.{}>'.format(self.value)


class Ctap2Version(enum.Enum):
    CTAP2_0 = 'ctap2_0'
    CTAP2_1 = 'ctap2_1'

    @classmethod
    def from_json(cls, json: str) ->Ctap2Version:
        return cls(json)

    def to_json(self) ->str:
        return self.value

    def __repr__(self) ->str:
        return '<Ctap2Version.{}>'.format(self.value)


class AuthenticatorId(str):
    """Represents the CDP type 'WebAuthn.AuthenticatorId'."""

    def to_json(self) ->str:
        return self

    @classmethod
    def from_json(cls, json: str) ->AuthenticatorId:
        return cls(json)

    def __repr__(self) ->str:
        return 'AuthenticatorId({})'.format(super().__repr__())


def add_credential(authenticator_id: AuthenticatorId, credential: Credential
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Adds the credential to the specified authenticator.

:param ...:

:param authenticator_id:

:param credential:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['credential'] = credential.to_json()
    cmd_dict = {'method': 'WebAuthn.addCredential', 'params': params_dict}
    json_result = yield cmd_dict
    return None


def add_virtual_authenticator(options: VirtualAuthenticatorOptions
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, AuthenticatorId]:
    """Creates and adds a virtual authenticator.

:param ...:

:param options:


:returns:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['options'] = options.to_json()
    cmd_dict = {'method': 'WebAuthn.addVirtualAuthenticator', 'params':
        params_dict}
    json_result = yield cmd_dict
    return AuthenticatorId.from_json(json_result['authenticatorId'])


def clear_credentials(authenticator_id: AuthenticatorId) ->typing.Generator[
    T_JSON_DICT, T_JSON_DICT, None]:
    """Clears all the credentials from the specified device.

:param ...:

:param authenticator_id:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    cmd_dict = {'method': 'WebAuthn.clearCredentials', 'params': params_dict}
    json_result = yield cmd_dict
    return None


def disable() ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Disable the WebAuthn domain."""
    cmd_dict = {'method': 'WebAuthn.disable'}
    json_result = yield cmd_dict
    return None


def enable(enable_ui: typing.Optional[bool]=None) ->typing.Generator[
    T_JSON_DICT, T_JSON_DICT, None]:
    """Enable the WebAuthn domain and start intercepting credential storage and
retrieval with a virtual authenticator.

:param ...:

:param enable_ui: *(Optional)* Whether to enable the WebAuthn user interface. Enabling the UI is recommended for debugging and demo purposes, as it is closer to the real experience. Disabling the UI is recommended for automated testing. Supported at the embedder's discretion if UI is available. Defaults to false."""
    params_dict: T_JSON_DICT = dict()
    if enable_ui is not None:
        params_dict['enableUI'] = enable_ui
    cmd_dict = {'method': 'WebAuthn.enable', 'params': params_dict}
    json_result = yield cmd_dict
    return None


def get_credential(authenticator_id: AuthenticatorId, credential_id: str
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, Credential]:
    """Returns a single credential stored in the given virtual authenticator that
matches the credential ID.

:param ...:

:param authenticator_id:

:param credential_id:


:returns:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['credentialId'] = credential_id
    cmd_dict = {'method': 'WebAuthn.getCredential', 'params': params_dict}
    json_result = yield cmd_dict
    return Credential.from_json(json_result['credential'])


def get_credentials(authenticator_id: AuthenticatorId) ->typing.Generator[
    T_JSON_DICT, T_JSON_DICT, typing.List[Credential]]:
    """Returns all the credentials stored in the given virtual authenticator.

:param ...:

:param authenticator_id:


:returns:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    cmd_dict = {'method': 'WebAuthn.getCredentials', 'params': params_dict}
    json_result = yield cmd_dict
    return [Credential.from_json(i) for i in json_result['credentials']]


def remove_credential(authenticator_id: AuthenticatorId, credential_id: str
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Removes a credential from the authenticator.

:param ...:

:param authenticator_id:

:param credential_id:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['credentialId'] = credential_id
    cmd_dict = {'method': 'WebAuthn.removeCredential', 'params': params_dict}
    json_result = yield cmd_dict
    return None


def remove_virtual_authenticator(authenticator_id: AuthenticatorId
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Removes the given authenticator.

:param ...:

:param authenticator_id:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    cmd_dict = {'method': 'WebAuthn.removeVirtualAuthenticator', 'params':
        params_dict}
    json_result = yield cmd_dict
    return None


def set_automatic_presence_simulation(authenticator_id: AuthenticatorId,
    enabled: bool) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Sets whether tests of user presence will succeed immediately (if true) or fail to resolve (if false) for an authenticator.
The default is true.

:param ...:

:param authenticator_id:

:param enabled:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['enabled'] = enabled
    cmd_dict = {'method': 'WebAuthn.setAutomaticPresenceSimulation',
        'params': params_dict}
    json_result = yield cmd_dict
    return None


def set_credential_properties(authenticator_id: AuthenticatorId,
    credential_id: str, backup_eligibility: typing.Optional[bool]=None,
    backup_state: typing.Optional[bool]=None) ->typing.Generator[
    T_JSON_DICT, T_JSON_DICT, None]:
    """Allows setting credential properties.
https://w3c.github.io/webauthn/#sctn-automation-set-credential-properties

:param ...:

:param authenticator_id:

:param credential_id:

:param backup_eligibility: *(Optional)*

:param backup_state: *(Optional)*"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['credentialId'] = credential_id
    if backup_eligibility is not None:
        params_dict['backupEligibility'] = backup_eligibility
    if backup_state is not None:
        params_dict['backupState'] = backup_state
    cmd_dict = {'method': 'WebAuthn.setCredentialProperties', 'params':
        params_dict}
    json_result = yield cmd_dict
    return None


def set_response_override_bits(authenticator_id: AuthenticatorId,
    is_bogus_signature: typing.Optional[bool]=None, is_bad_uv: typing.
    Optional[bool]=None, is_bad_up: typing.Optional[bool]=None
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Resets parameters isBogusSignature, isBadUV, isBadUP to false if they are not present.

:param ...:

:param authenticator_id:

:param is_bogus_signature: *(Optional)* If isBogusSignature is set, overrides the signature in the authenticator response to be zero. Defaults to false.

:param is_bad_uv: *(Optional)* If isBadUV is set, overrides the UV bit in the flags in the authenticator response to be zero. Defaults to false.

:param is_bad_up: *(Optional)* If isBadUP is set, overrides the UP bit in the flags in the authenticator response to be zero. Defaults to false."""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    if is_bogus_signature is not None:
        params_dict['isBogusSignature'] = is_bogus_signature
    if is_bad_uv is not None:
        params_dict['isBadUV'] = is_bad_uv
    if is_bad_up is not None:
        params_dict['isBadUP'] = is_bad_up
    cmd_dict = {'method': 'WebAuthn.setResponseOverrideBits', 'params':
        params_dict}
    json_result = yield cmd_dict
    return None


def set_user_verified(authenticator_id: AuthenticatorId, is_user_verified: bool
    ) ->typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    """Sets whether User Verification succeeds or fails for an authenticator.
The default is true.

:param ...:

:param authenticator_id:

:param is_user_verified:"""
    params_dict: T_JSON_DICT = dict()
    params_dict['authenticatorId'] = authenticator_id.to_json()
    params_dict['isUserVerified'] = is_user_verified
    cmd_dict = {'method': 'WebAuthn.setUserVerified', 'params': params_dict}
    json_result = yield cmd_dict
    return None


@event_class('WebAuthn.credentialAdded')
@dataclass
class CredentialAdded:
    """Triggered when a credential is added to an authenticator."""
    authenticator_id: AuthenticatorId
    credential: Credential

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->CredentialAdded:
        return cls(authenticator_id=AuthenticatorId.from_json(json_obj[
            'authenticatorId']), credential=Credential.from_json(json_obj[
            'credential']))


@event_class('WebAuthn.credentialAsserted')
@dataclass
class CredentialAsserted:
    """Triggered when a credential is used in a webauthn assertion."""
    authenticator_id: AuthenticatorId
    credential: Credential

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->CredentialAsserted:
        return cls(authenticator_id=AuthenticatorId.from_json(json_obj[
            'authenticatorId']), credential=Credential.from_json(json_obj[
            'credential']))


@event_class('WebAuthn.credentialDeleted')
@dataclass
class CredentialDeleted:
    """Triggered when a credential is deleted, e.g. through
PublicKeyCredential.signalUnknownCredential()."""
    authenticator_id: AuthenticatorId
    credential_id: str

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->CredentialDeleted:
        return cls(authenticator_id=AuthenticatorId.from_json(json_obj[
            'authenticatorId']), credential_id=json_obj['credentialId'])


@event_class('WebAuthn.credentialUpdated')
@dataclass
class CredentialUpdated:
    """Triggered when a credential is updated, e.g. through
PublicKeyCredential.signalCurrentUserDetails()."""
    authenticator_id: AuthenticatorId
    credential: Credential

    @classmethod
    def from_json(cls, json_obj: T_JSON_DICT) ->CredentialUpdated:
        return cls(authenticator_id=AuthenticatorId.from_json(json_obj[
            'authenticatorId']), credential=Credential.from_json(json_obj[
            'credential']))
